### ISSUE TITLE
Shared volume does not contain every directory

### ISSUE THREAD

**Issue by sd-lueckel** [solutionDrive/sdTestEnvironmentShopware#6]
After the start of the test environment, the shared directory does not contain every directory from the different shopware containers!

Steps to reproduce:
`vendor/bin/sdTest.sh start`
`docker exec -it <projectname>_shopware546_php70_1 /bin/bash`
`ls -ahl /var/www`

Current output:
`html              shopware54_php71`

Expected output:
`html              shopware54_php70              shopware54_php71              shopware54_php72`

**Comment by michz** [comment]
Ah okay, so there seem to be problem creating the directories/links...

**Comment by sd-lueckel** [comment]
Yeah, it seems only 1 container wins the race and copy its content from /var/www to the shared directory
